"""empty message

Revision ID: 0bd4061c0601
Revises: 97bd13e6f6d6
Create Date: 2021-05-12 10:07:45.818677

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0bd4061c0601'
down_revision = '97bd13e6f6d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cms_banner', 'priority')
    op.drop_index('email', table_name='cms_user')
    op.drop_column('cms_user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('email', mysql.VARCHAR(length=100), nullable=True))
    op.create_index('email', 'cms_user', ['email'], unique=True)
    op.add_column('cms_banner', sa.Column('priority', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
