"""empty message

Revision ID: 446a06c73e8a
Revises: 74231d4187ce
Create Date: 2021-01-27 20:01:12.647145

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '446a06c73e8a'
down_revision = '74231d4187ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('essence_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('posts_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['posts_id'], ['front_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('essence_posts_model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('essence_posts_model',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('posts_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['posts_id'], ['front_posts.id'], name='essence_posts_model_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('essence_posts')
    # ### end Alembic commands ###
