"""empty message

Revision ID: 55e636b32754
Revises: c970b52d709b
Create Date: 2021-02-02 15:13:50.325448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55e636b32754'
down_revision = 'c970b52d709b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('is_delete', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cms_user', 'is_delete')
    # ### end Alembic commands ###
