"""empty message

Revision ID: 74231d4187ce
Revises: 42aaa123515b
Create Date: 2021-01-27 20:00:22.333267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74231d4187ce'
down_revision = '42aaa123515b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('essence_posts_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('posts_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['posts_id'], ['front_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('essence_posts_model')
    # ### end Alembic commands ###
