"""empty message

Revision ID: 877314b6cd77
Revises: b492913363df
Create Date: 2021-01-26 15:27:18.639375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '877314b6cd77'
down_revision = 'b492913363df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cms_board',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cms_board')
    # ### end Alembic commands ###
