"""empty message

Revision ID: 8a2471d31478
Revises: 55e636b32754
Create Date: 2021-02-05 16:44:48.834790

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8a2471d31478'
down_revision = '55e636b32754'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='front_user')
    op.drop_column('front_user', 'email')
    op.drop_column('front_user', 'realname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('front_user', sa.Column('realname', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('front_user', sa.Column('email', mysql.VARCHAR(length=100), nullable=True))
    op.create_index('email', 'front_user', ['email'], unique=True)
    # ### end Alembic commands ###
