"""empty message

Revision ID: 97bd13e6f6d6
Revises: b9dfa4f221e9
Create Date: 2021-05-12 10:03:58.896698

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '97bd13e6f6d6'
down_revision = 'b9dfa4f221e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('front_user', 'signature')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('front_user', sa.Column('signature', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
