"""empty message

Revision ID: 9ba29b013220
Revises: 0bd4061c0601
Create Date: 2021-05-12 11:12:01.543212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ba29b013220'
down_revision = '0bd4061c0601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('email', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'cms_user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cms_user', type_='unique')
    op.drop_column('cms_user', 'email')
    # ### end Alembic commands ###
