"""empty message

Revision ID: c2cf341ced91
Revises: eeb37222fdcd
Create Date: 2021-01-28 20:17:06.339139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2cf341ced91'
down_revision = 'eeb37222fdcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('front_posts', sa.Column('read_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('front_posts', 'read_count')
    # ### end Alembic commands ###
