"""empty message

Revision ID: c970b52d709b
Revises: c2cf341ced91
Create Date: 2021-01-29 15:22:33.061444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c970b52d709b'
down_revision = 'c2cf341ced91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('front_posts', sa.Column('like_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('front_posts', 'like_count')
    # ### end Alembic commands ###
